name: OverniteProduction
favicon: null
layout_spectrum: 0.6378435709048063
typography_spectrum: 0.3537258659489453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5935707988683134
  lightness: 0.34649457409977913
  saturation: 0.41872142325155437
  rhythmicContrast: 0.3019490472506732
purpose: []
